### ISSUE TITLE
Plugins download links are broken

### ISSUE THREAD

**Issue by fsherstobitov** [hhru/android-multimodule-plugin#38]
When I'm clicking on the links in the [README](https://github.com/hhru/android-multimodule-plugin), like the [hh-geminio](https://github.com/hhru/android-multimodule-plugin/blob/master/distr/hh-geminio.zip) link, I get the 404 GitHub page. Please, provide the links for the current plugins binaries.

**Comment by PStrelchenko** [comment]
@fsherstobitov , thanks for opening this one.

I've decided to remove zip-artifacts from this repository because some people faced with strange issues of using plugins on OS that differ from macOS. 
A more reliable solution for you - build zip archives of plugins by yourself on your machine with `./gradlew :plugins:hh-geminio:buildPlugin` Gradle-task.

Links will be removed from README.

Thanks!
